version: '3.7'
services:
  mysql-docker:
    image: mysql:${MYSQL_IMAGE_VERSION}
    container_name: mysql-docker
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
