version: '3.7'
services:
  postgres-docker:
    image: postgres:${POSTGRES_IMAGE_VERSION}
    container_name: postgres-docker
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data