version: '3.7'
services:
  redis-json-docker:
    image: redislabs/rejson:${REJSON_IMAGE_VERSION}
    container_name: redis-json-docker
    command: redis-server --requirepass ${REJSON_PASSWORD} --loadmodule /usr/lib/redis/modules/rejson.so
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
  redis-commander-docker:
    image: ghcr.io/joeferner/redis-commander:latest
    container_name: redis-commander-docker
    environment:
      - REDIS_HOST=redis-json-docker
      - REDIS_PORT=6379
      - REDIS_PASSWORD=mouse
    ports:
      - 8081:8081
